name: Run_test_Pre-commit

on:
  push:
    branches: ['Frankie-Restructure']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pycalc
        pip show pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run tests with pytest
      run: |
        pytest
